# This is pretty useless, but it sets the version of the build
version: 0.0.0.build.{build}

# Force configuration
configuration: Debug

# Use Visual Studio 2015 base image
image: Visual Studio 2015

# enforce the location, since we want predictable cmake things
clone_folder: c:\projects\osslugaru\lugaru

# Build for 32-bit target only
platform:
  - Win32

# Prep work (CMake VS project generation)
before_build:
  - cd c:\projects\osslugaru\lugaru
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\BIN;%PATH%
  - if %PLATFORM% == Win32 cmake . -DCMAKE_BUILD_TYPE=Debug -DLUGARU_INSTALL_PREFIX=C:\projects\osslugaru\lugaru\msvc32-build -DLUGARU_FORCE_INTERNAL_SDL=True -DLUGARU_FORCE_INTERNAL_GLU=True -DLUGARU_FORCE_INTERNAL_JPEG=True -DLUGARU_FORCE_INTERNAL_PNG=True -DLUGARU_FORCE_INTERNAL_VORBIS=True -DLUGARU_FORCE_INTERNAL_ZLIB=True -DLUGARU_FORCE_INTERNAL_OPENAL=True

# Tell it what to build
build:
  project: lugaru.sln
  parallel: true
