image: fedora:latest

cache:
  key: dnf
  paths:
  - /var/cache/dnf

before_script:
  - dnf --quiet --assumeyes install /usr/bin/cmake "pkgconfig(libjpeg)" "pkgconfig(openal)" "pkgconfig(sdl2)" "pkgconfig(glu)" "pkgconfig(libpng)" "pkgconfig(zlib)" "pkgconfig(vorbis)" "pkgconfig(vorbisfile)" "pkgconfig(ogg)" make

build_gcc:
  stage: build
  script:
    - dnf --quiet --assumeyes install gcc gcc-c++
    - export CC=gcc; export CXX=g++
    - mkdir -p x86_64-linux-gnu-gcc gcc-build; cd x86_64-linux-gnu-gcc
    - cmake .. -DCMAKE_INSTALL_PREFIX=/builds/osslugaru/lugaru/gcc-build
    - make -j4; make install
  artifacts:
    expire_in: 7d
    paths:
      - ./gcc-build
  tags:
    - shared

build_clang:
  stage: build
  script:
    - dnf --quiet --assumeyes install clang
    - export CC=clang; export CXX=clang++
    - mkdir -p x86_64-linux-gnu-clang clang-build; cd x86_64-linux-gnu-clang
    - cmake .. -DCMAKE_INSTALL_PREFIX=/builds/osslugaru/lugaru/clang-build
    - make -j4; make install
  artifacts:
    expire_in: 7d
    paths:
      - ./clang-build
  tags:
    - shared

build_mingw32:
  stage: build
  script:
    - dnf --quiet --assumeyes install "dnf-command(copr)"
    - dnf --assumeyes copr enable ngompa/mingw-openal-soft
    - dnf --quiet --assumeyes install mingw32-gcc mingw32-gcc-c++ mingw32-binutils mingw32-headers mingw32-libjpeg-turbo mingw32-libpng mingw32-SDL2 mingw32-zlib mingw32-libvorbis mingw32-libogg mingw32-openal-soft
    - export PKG_CONFIG_LIBDIR="/usr/i686-w64-mingw32/sys-root/mingw/lib/pkgconfig:/usr/i686-w64-mingw32/sys-root/mingw/share/pkgconfig"
    - export PATH=/usr/i686-w64-mingw32/bin:$PATH
    - mkdir -p i686-w64-mingw32 mingw32-build; cd i686-w64-mingw32
    - cmake .. -DCMAKE_TOOLCHAIN_FILE=/usr/share/mingw/toolchain-mingw32.cmake -DCMAKE_INSTALL_PREFIX=/builds/osslugaru/lugaru/mingw32-build
    - make -j4; make install
  artifacts:
    expire_in: 7d
    paths:
      - ./mingw32-build
  tags:
    - shared

build_mingw64:
  stage: build
  script:
    - dnf --quiet --assumeyes install "dnf-command(copr)"
    - dnf --assumeyes copr enable ngompa/mingw-openal-soft
    - dnf --quiet --assumeyes install mingw64-gcc mingw64-gcc-c++ mingw64-binutils mingw64-headers mingw64-libjpeg-turbo mingw64-libpng mingw64-SDL2 mingw64-zlib mingw64-libvorbis mingw64-libogg mingw64-openal-soft
    - export PKG_CONFIG_LIBDIR="/usr/x86_64-w64-mingw32/sys-root/mingw/lib/pkgconfig:/usr/x86_64-w64-mingw32/sys-root/mingw/share/pkgconfig"
    - export PATH=/usr/x86_64-w64-mingw32/bin:$PATH
    - mkdir -p x86_64-w64-mingw32 mingw64-build; cd x86_64-w64-mingw32
    - cmake .. -DCMAKE_TOOLCHAIN_FILE=/usr/share/mingw/toolchain-mingw64.cmake -DCMAKE_INSTALL_PREFIX=/builds/osslugaru/lugaru/mingw64-build
    - make -j4; make install
  artifacts:
    expire_in: 7d
    paths:
      - ./mingw64-build
  tags:
    - shared

